name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t assignment-nginx .

      - name: Run Container
        run: docker run -d --name assignment-container -p 8080:80 assignment-nginx

  logs:
    runs-on: ubuntu-latest
    needs: build
    steps:
      
      - name: Show Container Logs
        run:  docker logs assignment-container


  deploy:
    runs-on: ubuntu-latest
    needs: logs

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Curl localhost:8080
        run: curl http://localhost:8080

      - name: Verify Custom Content
        run: curl http://localhost:8080 | grep "Hello Sumit!"
